### ISSUE TITLE
List index out of range of main page 

### ISSUE THREAD

**Issue by nyLiao** [nyLiao/SJTUsousou#5]
Seems that blog need to handle the situation when database is empty. 

### Traceback:
```
Request Method: GET
Request URL: http://127.0.0.1:8000/

Django Version: 3.0.3
Python Version: 3.7.3
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'haystack',
 'soso',
 'blog',
 'ckeditor',
 'ckeditor_uploader',
 'mdeditor',
 'captcha']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback (most recent call last):
  File "/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/SJTUsousou/SJTUsoso/blog/views.py", line 346, in tohome
    latest_msg_board0 = MessageBoard.objects.order_by('-create_time')[0]
  File "/lib/python3.7/site-packages/django/db/models/query.py", line 314, in __getitem__
    return qs._result_cache[0]

Exception Type: IndexError at /
Exception Value: list index out of range
```

**Comment by nyLiao** [comment]
Looks like f6ff83963a95249ea839579f93275c0ebebd7995 fixes it. Thx.
